apiVersion: v1
kind: Template
labels:
  app: httpexporter
  template: httpexporter-imagestream
metadata:
  annotations:
    description: Apache Exporter - ImageStream
      see https://github.com/Worteks/docker-httpexporter
    iconClass: icon-openshift
    openshift.io/display-name: Apache Exporter
    tags: httpexporter
  name: httpexporter-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Apache Exporter image
    name: httpexporter-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
